### ISSUE TITLE
CLArray testing problem

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/OpenCL.jl#91] opened 2015-11-17 06:51 UTC
Besides the OOM problem on travis I am also running into this:

````
  > OpenCL.CLArray transpose
ERROR: LoadError: LoadError: CLError(code=-30, CL_INVALID_VALUE)
 [inlined code] from /home/wallnuss/.julia/v0.4/OpenCL/src/macros.jl:6
 in enqueue_kernel at /home/wallnuss/.julia/v0.4/OpenCL/src/kernel.jl:5
 in transpose! at /home/wallnuss/.julia/v0.4/OpenCL/src/array.jl:106
 in anonymous at /home/wallnuss/.julia/v0.4/OpenCL/test/test_array.jl:59
````

on a `OpenCL.Device(NVS 4200M on NVIDIA CUDA)`

**Comment by nstiurca** [comment] 2015-12-07 16:56
Once #98 is merged, see if that makes a difference.

I'm finding OpenCL to be a very fickle mistress though. For me, all tests run ok using NVIDIA GTX 860M device, but using `OpenCL.Device(Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz on Intel(R) OpenCL)` yields

<pre><code> <... SNIP ...>
OpenCL.CLArray
  > OpenCL.CLArray constructors
  > OpenCL.CLArray fill
  > OpenCL.CLArray core functions
ERROR: LoadError: LoadError: CLError(code=-38, CL_INVALID_MEM_OBJECT)
 [inlined code] from /home/nstiurca/.julia/v0.4/OpenCL/src/macros.jl:6
 in set_arg! at /home/nstiurca/.julia/v0.4/OpenCL/src/kernel.jl:75
 in set_args! at /home/nstiurca/.julia/v0.4/OpenCL/src/kernel.jl:105
 in transpose! at /home/nstiurca/.julia/v0.4/OpenCL/src/array.jl:107
 in anonymous at /home/nstiurca/.julia/v0.4/OpenCL/test/test_array.jl:58
 in context at /home/nstiurca/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /home/nstiurca/.julia/v0.4/OpenCL/test/test_array.jl:41
 in facts at /home/nstiurca/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/nstiurca/.julia/v0.4/OpenCL/test/test_array.jl, in expression starting on line 3
while loading /home/nstiurca/.julia/v0.4/OpenCL/test/runtests.jl, in expression starting on line 29</code></pre>

**Comment by dfdx** [comment] 2015-12-07 22:33
Seems like both of these issues refer to `transpose!()`. This function was implemented using Python notebook from `examples/` without paying attention to details, so now I see several gross mistakes in it. I'm working on it and will post an update soon.

**Comment by dfdx** [comment] 2016-01-02 18:38
@vchuravy @nstiurca Could you please check if this issue is reproducible using latest master?

**Comment by nstiurca** [comment] 2016-01-02 19:03
I'll try to have a look this weekend.

**Comment by rafaelcp** [comment] 2016-02-05 07:26
Just updated to latest master and got:

> ERROR: LoadError: LoadError: CLError(code=-11, CL_BUILD_PROGRAM_FAILURE)
 [inlined code] from C:\Users\Rafael\.julia\v0.4\OpenCL\src\macros.jl:6
 in build! at C:\Users\Rafael\.julia\v0.4\OpenCL\src\program.jl:81
 in build_kernel at C:\Users\Rafael\.julia\v0.4\OpenCL\src\util.jl:41
 in get_kernel at C:\Users\Rafael\.julia\v0.4\OpenCL\src\util.jl:54
 in transpose! at C:\Users\Rafael\.julia\v0.4\OpenCL\src\array.jl:111
 in anonymous at C:\Users\Rafael\.julia\v0.4\OpenCL\test\test_array.jl:55
 in context at C:\Users\Rafael\.julia\v0.4\FactCheck\src\FactCheck.jl:474
 in anonymous at C:\Users\Rafael\.julia\v0.4\OpenCL\test\test_array.jl:41
 in facts at C:\Users\Rafael\.julia\v0.4\FactCheck\src\FactCheck.jl:448
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in process_options at client.jl:280
 in _start at client.jl:378
while loading C:\Users\Rafael\.julia\v0.4\OpenCL\test\test_array.jl, in expressi
on starting on line 3
while loading C:\Users\Rafael\.julia\v0.4\OpenCL\test\runtests.jl, in expression
 starting on line 29

**Comment by rafaelcp** [comment] 2016-02-05 20:01
After including #98, I got:

> ERROR: LoadError: LoadError: CLError(code=-38, CL_INVALID_MEM_OBJECT)
 [inlined code] from C:\Users\Rafael\.julia\v0.4\OpenCL\src\macros.jl:6
 in set_arg! at C:\Users\Rafael\.julia\v0.4\OpenCL\src\kernel.jl:75
 in set_args! at C:\Users\Rafael\.julia\v0.4\OpenCL\src\kernel.jl:105
 in transpose! at C:\Users\Rafael\.julia\v0.4\OpenCL\src\array.jl:107
 in anonymous at C:\Users\Rafael\.julia\v0.4\OpenCL\test\test_array.jl:55
 in context at C:\Users\Rafael\.julia\v0.4\FactCheck\src\FactCheck.jl:474
 in anonymous at C:\Users\Rafael\.julia\v0.4\OpenCL\test\test_array.jl:41
 in facts at C:\Users\Rafael\.julia\v0.4\FactCheck\src\FactCheck.jl:448
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in process_options at client.jl:280
 in _start at client.jl:378
while loading C:\Users\Rafael\.julia\v0.4\OpenCL\test\test_array.jl, in expressi
on starting on line 3
while loading C:\Users\Rafael\.julia\v0.4\OpenCL\test\runtests.jl, in expression
 starting on line 29

**Comment by rafaelcp** [comment] 2016-02-05 20:14
More info just before the error:

> (device,ctx) = (OpenCL.Device(Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz on Intel(
R) OpenCL @0x000000000eb19240),OpenCL.Context(@0x000000000eb1aba0 on Intel(R) Co
re(TM) i7-4510U CPU @ 2.00GHz))

**Comment by dfdx** [comment] 2016-02-05 20:55
@rafaelcp If you run the test several times, is this error always reproduced with exactly the same message? In general, #98 doesn't add anything new and both errors point to the same lines, but with different error codes, so it makes me think it might be subject for a chance.

**Comment by rafaelcp** [comment] 2016-02-05 21:09
@dfdx Yeah, I'm getting exactly the same result everytime.

**Comment by rafaelcp** [comment] 2016-02-05 21:25
I also get this after almost every test, although they don't fail:

> error in running finalizer: OpenCL.CLError(code=-58, desc=:CL_INVALID_EVENT)

**Comment by dfdx** [comment] 2016-02-05 21:30
What OpenCL implementation do you use? Is it possible for you to switch implementation (e.g. AMD <-> Intel)? Also, if you use AMD SDK 3.0 it makes sense to test earlier version (v2.9).

**Comment by rafaelcp** [comment] 2016-02-05 23:50
I have both AMD (3.0) and Intel here. I skipped the Intel platform in the test and it passed. The readme example is working too. So, I think while I keep using the AMD platform, everything will work as intended. Another time I'll see if my Intel SDK needs an update. Thanks!

**Closed** 2016-04-07 11:15 UTC
